<?php
/**
 * A place to store program constants and functions to easily access them
 */

/**
 * A method to get the url for help videos respectice of the current setting based on the given <code>$key</code>.
 * @param string $key The identifying key/name for the help video.
 * @return The (theoretically) correct URL to where the video is located based on the admin's preferences.
 */
function go_get_help_video_url($key){
	$go_YOUTUBE_HELP_URLS = array(
	'go_introduction_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',//placeholder URLs
	'go_admin_email_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_naming_conventions' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_tasks_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_stages_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_stages_buttons_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_settings_store_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_loot_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_bonus_loot_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_points_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_money_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_bonus_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_penalty_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_minutes_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_ranks_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_classifications_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_focus_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_stats_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_inventory_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_badges_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_leaderboard_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_loot_presets_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_loot_presets_names' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_loot_presets_points' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_loot_presets_money' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_add_preset_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_revert_presets_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_save_presets_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_admin_bar_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_admin_bar_display_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_admin_bar_redirect_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_admin_bar_add_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_admin_bar_add_minutes_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_levels_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_levels_name_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_levels_points_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_levels_badges_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_add_level_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_reset_level_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_levels_save_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_fix_levels_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_seating_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_periods_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_add_period_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_computer_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_add_computer_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_profession_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_profession_switch_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_profession_name_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_additional_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_video_size_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_email_from_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_confirmation_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_full_name_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_multiplier_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_multiplier_threshold_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_penalty_mechanism_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_penalty_threshold_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_multiplier_percentage_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_use_non_youtube_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_reset_everything_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_reset_everything_2_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_clipboard_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_presets_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_advanced_quest_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_rank_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_bonus_money_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_penalty_filter_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_start_filter_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_time_filter' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_date_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_time_nerf_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_profession_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_three_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_five_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_chain_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_chain_final_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_one_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_one_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_point_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_money_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_bonus_money_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_admin_lock_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_url_key_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_upload_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_encounter_check_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_return_points_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_return_loot_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_test_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_badge_help'=> 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_accept_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_two_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_accept_check_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_complete_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_three_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_complete_check_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_four_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_four_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_master_check_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_master_privacy_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_bonus_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_five_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_stage_five_settings_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_repeat_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_quest_repeat_privacy_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_cost_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_limit_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_bonus_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_debt_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_filter_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_exchange_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_url_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_badge_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_focus_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_focus_lock_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_email_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
	'go_store_gift_help' => 'https://www.youtube.com/watch?v=RaucEEi6yqY',
); 

$go_MACLAB_HELP_URLS = array(
	'go_introduction_help' => 'http://maclab.guhsd.net/go/video/gameOn.mp4',
	'go_admin_email_help' => 'http://maclab.guhsd.net/go/video/options/adminEmail.mp4',
	'go_naming_conventions' => 'http://maclab.guhsd.net/go/video/options/namingConventions.mp4',
	'go_tasks_help' => 'http://maclab.guhsd.net/go/video/options/tasks.mp4',
	'go_stages_help' => 'http://maclab.guhsd.net/go/video/options/stages.mp4',
	'go_stages_buttons_help' => 'http://maclab.guhsd.net/go/video/options/stageButtons.mp4',
	'go_settings_store_help' => 'http://maclab.guhsd.net/go/video/options/store.mp4',//video 404's
	'go_loot_help' => 'http://maclab.guhsd.net/go/video/options/taskLoot.mp4',//video 404's
	'go_bonus_loot_help' => 'http://maclab.guhsd.net/go/video/options/bonusLoot.mp4',//video 404's
	'go_points_help' => 'http://maclab.guhsd.net/go/video/options/points.mp4',
	'go_money_help' => 'http://maclab.guhsd.net/go/video/options/currency.mp4',
	'go_bonus_help' => 'http://maclab.guhsd.net/go/video/options/bonus.mp4',
	'go_penalty_help' => 'http://maclab.guhsd.net/go/video/options/penalty.mp4',
	'go_minutes_help' => 'http://maclab.guhsd.net/go/video/options/minutes.mp4',//video 404's
	'go_ranks_help' => 'http://maclab.guhsd.net/go/video/options/ranks.mp4',
	'go_classifications_help' => 'http://maclab.guhsd.net/go/video/options/classifications.mp4',
	'go_focus_help' => 'http://maclab.guhsd.net/go/video/options/focus.mp4',
	'go_stats_help' => 'http://maclab.guhsd.net/go/video/options/stats.mp4',
	'go_inventory_help' => 'http://maclab.guhsd.net/go/video/options/inventory.mp4',
	'go_badges_help' => 'http://maclab.guhsd.net/go/video/options/badges.mp4',
	'go_leaderboard_help' => 'http://maclab.guhsd.net/go/video/options/leaderboard.mp4',
	'go_loot_presets_help' => 'http://maclab.guhsd.net/go/video/options/lootPresets.mp4',
	'go_loot_presets_names' => 'http://maclab.guhsd.net/go/video/options/presetName.mp4',
	'go_loot_presets_points' => 'http://maclab.guhsd.net/go/video/options/presetPoints.mp4',
	'go_loot_presets_money' => 'http://maclab.guhsd.net/go/video/options/presetCurrency.mp4',
	'go_add_preset_help' => 'http://maclab.guhsd.net/go/video/options/addPreset.mp4',
	'go_revert_presets_help' => 'http://maclab.guhsd.net/go/video/options/resetPresets.mp4',
	'go_save_presets_help' => 'http://maclab.guhsd.net/go/video/options/savePresets.mp4',
	'go_admin_bar_help' => 'http://maclab.guhsd.net/go/video/options/adminBar.mp4',
	'go_admin_bar_diaplay_help' => 'http://maclab.guhsd.net/go/video/options/adminBarDisplay.mp4',
	'go_admin_bar_redirect_help' => 'http://maclab.guhsd.net/go/video/options/userRedirect.mp4',
	'go_admin_bar_add_help' => 'http://maclab.guhsd.net/go/video/options/adminBarAddSwitch.mp4',
	'go_admin_bar_add_minutes_help' => 'http://maclab.guhsd.net/go/video/options/adminBarAddMinutesOnly.mp4',
	'go_levels_help' => 'http://maclab.guhsd.net/go/video/options/levels.mp4',
	'go_levels_name_help' => 'http://maclab.guhsd.net/go/video/options/levelName.mp4',
	'go_levels_points_help' => 'http://maclab.guhsd.net/go/video/options/levelPoints.mp4',
	'go_levels_badges_help' => 'http://maclab.guhsd.net/go/video/options/levelBadges.mp4',
	'go_add_level_help' => 'http://maclab.guhsd.net/go/video/options/addLevel.mp4',
	'go_reset_level_help' => 'http://maclab.guhsd.net/go/video/options/resetLevels.mp4',
	'go_levels_save_help' => 'http://maclab.guhsd.net/go/video/options/saveLevels.mp4',
	'go_fix_levels_help' => 'http://maclab.guhsd.net/go/video/options/fixLevels.mp4',
	'go_seating_help' => 'http://maclab.guhsd.net/go/video/options/seatingChart.mp4',
	'go_periods_help' => 'http://maclab.guhsd.net/go/video/options/periods.mp4',
	'go_add_period_help' => 'http://maclab.guhsd.net/go/video/options/addPeriod.mp4',
	'go_computer_help' => 'http://maclab.guhsd.net/go/video/options/computers.mp4',
	'go_add_computer_help' => 'http://maclab.guhsd.net/go/video/options/addComputer.mp4',
	'go_profession_help' => 'http://maclab.guhsd.net/go/video/options/profession.mp4',
	'go_profession_switch_help' => 'http://maclab.guhsd.net/go/video/options/professionSwitch.mp4',
	'go_profession_name_help' => 'http://maclab.guhsd.net/go/video/options/professionName.mp4',
	'go_additional_settings_help' => 'http://maclab.guhsd.net/go/video/options/additionalSettings.mp4',
	'go_video_size_help' => 'http://maclab.guhsd.net/go/video/options/videoDefault.mp4',
	'go_email_from_help' => 'http://maclab.guhsd.net/go/video/options/emailFrom.mp4',//video 404's
	'go_confirmation_help' => 'http://maclab.guhsd.net/go/video/options/storeReceipt.mp4',
	'go_full_name_help' => 'http://maclab.guhsd.net/go/video/options/fullStudentName.mp4',
	'go_multiplier_help' => 'http://maclab.guhsd.net/go/video/options/multiplier.mp4',
	'go_multiplier_threshold_help' => 'http://maclab.guhsd.net/go/video/options/multiplierThreshold.mp4',
	'go_penalty_mechanism_help' => 'http://maclab.guhsd.net/go/video/options/penalty2.mp4',
	'go_penalty_threshold_help' => 'http://maclab.guhsd.net/go/video/options/penaltyThreshold.mp4',
	'go_multiplier_percentage_help' => 'http://maclab.guhsd.net/go/video/options/multiplierPercentage.mp4',
	'go_use_non_youtube_help' => '', //no video yet
	'go_reset_everything_help' => 'http://maclab.guhsd.net/go/video/options/dataReset.mp4',
	'go_reset_everything_2_help' => 'http://maclab.guhsd.net/go/video/options/dataReset2.mp4',
	'go_clipboard_help' => 'http://maclab.guhsd.net/go/video/clipboard/clipboard.mp4', //currently a 404
	'go_presets_help' => 'http://maclab.guhsd.net/go/video/quests/presets.mp4',
	'go_advanced_quest_settings_help' => 'http://maclab.guhsd.net/go/video/quests/advancedSettings.mp4',
	'go_quest_rank_help' => 'http://maclab.guhsd.net/go/video/quests/requiredRank.mp4',
	'go_quest_bonus_money_help' => 'http://maclab.guhsd.net/go/video/quests/bonusCurrencyFilter.mp4',
	'go_quest_penalty_filter_help' => 'http://maclab.guhsd.net/go/video/quests/penaltyFilter.mp4',
	'go_quest_start_filter_help' => 'http://maclab.guhsd.net/go/video/quests/startFilter.mp4',//video 404's
	'go_quest_time_filter' => 'http://maclab.guhsd.net/go/video/quests/timeFilter.mp4',
	'go_quest_date_help' => 'http://maclab.guhsd.net/go/video/quests/nerfDates.mp4',
	'go_quest_time_nerf_help' => 'http://maclab.guhsd.net/go/video/quests/nerfTime.mp4',
	'go_quest_profession_help' => ' http://maclab.guhsd.net/go/video/quests/lockByProfessionCategory.mp4',
	'go_quest_three_help' => 'http://maclab.guhsd.net/go/video/quests/threeStageQuest.mp4',
	'go_quest_five_help' => 'http://maclab.guhsd.net/go/video/quests/fiveStageQuest.mp4',
	'go_quest_chain_help' => 'http://maclab.guhsd.net/go/video/quests/tasksInChain.mp4',
	'go_quest_chain_final_help' => 'http://maclab.guhsd.net/go/video/quests/finalChainMessage.mp4',
	'go_quest_stage_one_help' => 'http://maclab.guhsd.net/go/video/quests/stageOne.mp4',
	'go_quest_stage_one_settings_help' => 'http://maclab.guhsd.net/go/video/quests/stageOneSettings.mp4',
	'go_quest_stage_point_help' => 'http://maclab.guhsd.net/go/video/quests/stagePoint.mp4',
	'go_quest_stage_money_help' => 'http://maclab.guhsd.net/go/video/quests/stageCurrency.mp4',
	'go_quest_stage_bonus_money_help' => 'http://maclab.guhsd.net/go/video/quests/stageBonusCurrency.mp4',
	'go_quest_admin_lock_help' => 'http://maclab.guhsd.net/go/video/quests/adminLock.mp4',
	'go_quest_url_key_help' => 'http://maclab.guhsd.net/go/video/quests/urlKey.mp4',//video 404's
	'go_quest_upload_help' => 'http://maclab.guhsd.net/go/video/quests/fileUpload.mp4',
	'go_quest_encounter_check_help' => 'http://maclab.guhsd.net/go/video/quests/encounterCheckForUnderstanding.mp4',
	'go_quest_return_points_help' => 'http://maclab.guhsd.net/go/video/quests/returnPoints.mp4',
	'go_quest_return_loot_help' => 'http://maclab.guhsd.net/go/video/quests/returnModifier.mp4',
	'go_quest_test_help' => 'http://maclab.guhsd.net/go/video/quests/testFields.mp4',
	'go_quest_badge_help' => 'http://maclab.guhsd.net/go/video/quests/badge.mp4',//video 404's
	'go_quest_accept_help' => 'http://maclab.guhsd.net/go/video/quests/acceptMessage.mp4',
	'go_quest_two_settings_help' => 'http://maclab.guhsd.net/go/video/quests/stageTwoSettings.mp4',
	'go_quest_accept_check_help' => 'http://maclab.guhsd.net/go/video/quests/acceptCheckForUnderstanding.mp4',//video 404's
	'go_quest_complete_help' => 'http://maclab.guhsd.net/go/video/quests/completionMessage.mp4', 
	'go_quest_three_settings_help' => 'http://maclab.guhsd.net/go/video/quests/stageThreeSettings.mp4',
	'go_quest_complete_check_help' => 'http://maclab.guhsd.net/go/video/quests/completionCheckForUnderstanding.mp4',
	'go_quest_stage_four_help' => 'http://maclab.guhsd.net/go/video/quests/stageFour.mp4',
	'go_quest_four_settings_help' => 'http://maclab.guhsd.net/go/video/quests/stageFourSettings.mp4',
	'go_quest_master_check_help' => 'http://maclab.guhsd.net/go/video/quests/masteryCheckForUnderstanding.mp4',
	'go_quest_master_privacy_help' => 'http://maclab.guhsd.net/go/video/quests/masteryPrivacy.mp4',//video 404's
	'go_quest_bonus_help' => 'http://maclab.guhsd.net/go/video/quests/bonus.mp4',//video 404's
	'go_quest_stage_five_help' => 'http://maclab.guhsd.net/go/video/quests/stageFive.mp4',
	'go_quest_stage_five_settings_help' => 'http://maclab.guhsd.net/go/video/quests/stageFiveSettings.mp4',
	'go_quest_repeat_help' => 'http://maclab.guhsd.net/go/video/quests/allowedRepeatableTimes.mp4',
	'go_quest_repeat_privacy_help' => 'http://maclab.guhsd.net/go/video/quests/repeatPrivacy.mp4',//video 404's
	'go_store_help'=> 'http://maclab.guhsd.net/go/video/store/storeId.mp4',//video 404's
	'go_store_cost_help' => 'http://maclab.guhsd.net/go/video/store/cost.mp4',
	'go_store_limit_help' => 'http://maclab.guhsd.net/go/video/store/storeLimit.mp4',
	'go_store_bonus_help' => 'http://maclab.guhsd.net/go/video/store/bonus.mp4',//video 404's
	'go_store_debt_help' => 'http://maclab.guhsd.net/go/video/store/penalty.mp4',
	'go_store_filter_help' => 'http://maclab.guhsd.net/go/video/store/filter.mp4',
	'go_store_exchange_help' => 'http://maclab.guhsd.net/go/video/store/exchange.mp4',
	'go_store_url_help' => 'http://maclab.guhsd.net/go/video/store/itemURL.mp4',
	'go_store_badge_help' => 'http://maclab.guhsd.net/go/video/store/badgeID.mp4',
	'go_store_focus_help' => 'http://maclab.guhsd.net/go/video/store/focus.mp4',
	'go_store_focus_lock_help' => 'http://maclab.guhsd.net/go/video/store/focusLock.mp4',//video 404's
	'go_store_email_help' => 'http://maclab.guhsd.net/go/video/store/receipt.mp4',
	'go_store_gift_help' => 'http://maclab.guhsd.net/go/video/store/giftable.mp4',//video 404's
);
	if(get_option('go_use_maclab_help') == 'On'){
		//get the native non-youtube video
		return $go_MACLAB_HELP_URLS[$key];

	}else{
		//get the youtube video
		return $go_YOUTUBE_HELP_URLS[$key];

	}
}
?>